services:
  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - drf
#    healthcheck:
#      test: ['CMD_SHELL', 'pg-isready -U postgres']
#      interval: 30s
#      timeout: 10s
#      retries: 5
  redis:
    image: redis:latest
    networks:
      - drf
  celery:
    build: .
    command: poetry run celery -A config worker -l INFO
    networks:
      - drf
  celerybeat:
    build: .
    command: poetry run celery -A config beat -l INFO
    networks:
      - drf
  drf:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - '8000:8000'
    env_file:
      - .env
    networks:
      - drf
volumes:
  postgres_data:
  static_volume:
networks:
  drf:
