services:
  db:
    image: postgres:latest
    #env_file:
      #- .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - drf
#    healthcheck:
#      test: ['CMD_SHELL', 'pg-isready -U postgres']
#      interval: 30s
#      timeout: 10s
#      retries: 5
  redis:
    image: redis:latest
    networks:
      - drf
  celery:
    build: .
    command: poetry run celery -A config worker -l INFO
    networks:
      - drf
  celerybeat:
    build: .
    command: poetry run celery -A config beat -l INFO
    networks:
      - drf
  drf:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
      - static_volume:/code/static
    ports:
      - '8000:8000'
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=postgres://${USER}:${PASSWORD}@postgres:${PORT}/${NAME}
      - STRIPE_API_KEY=${STRIPE_API_KEY}
    #env_file:
      #- .env
    networks:
      - drf
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/nginx/staticfiles
    depends_on:
      - DRF
    networks:
      - DRF_network
volumes:
  postgres_data:
  static_volume:
networks:
  drf:
